repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=800"]
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.271"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, "--config", "pyproject.toml"]
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]
